/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import conexaoDB.ProdutoDB;
import conexaoDB.ServicoDB;
import entidades.Produto;
import entidades.Servico;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luanf
 */
public class ServicoView extends javax.swing.JFrame {

    /**
     * Creates new form ServicoView
     */
    public ServicoView() {
        initComponents();
        listarValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTipo = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        cadastrarServico = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaServico = new javax.swing.JTable();
        excluirServico = new javax.swing.JButton();
        apagarCampos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        alterarServico = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtFiltro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buscarFiltro = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        combo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastrarServico.setText("Cadastrar");
        cadastrarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarServicoActionPerformed(evt);
            }
        });

        tabelaServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Tipo", "Descricao", "Preco"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaServicoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaServico);

        excluirServico.setText("Excluir");
        excluirServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirServicoActionPerformed(evt);
            }
        });

        apagarCampos.setText("Apagar campos");
        apagarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarCamposActionPerformed(evt);
            }
        });

        jLabel1.setText("Id");

        alterarServico.setText("Alterar");
        alterarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarServicoActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo");

        jLabel3.setText("Preco");

        buscarFiltro.setText("Buscar");
        buscarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarFiltroActionPerformed(evt);
            }
        });

        txtId.setEditable(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Nome" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        jLabel4.setText("Descricao");

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(apagarCampos))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadastrarServico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alterarServico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirServico))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarFiltro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Voltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Voltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apagarCampos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarServico)
                    .addComponent(alterarServico)
                    .addComponent(excluirServico))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarFiltro)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarServicoActionPerformed
        // TODO add your handling code here:

        //Inseri um novo produto e atualiza a tabela

        cadastrarServico();
        listarValores();

    }//GEN-LAST:event_cadastrarServicoActionPerformed

    private void tabelaServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaServicoMouseClicked
        // TODO add your handling code here:

        //Carrega os valores dos campos para os campos de texto
        
        CarregarServico();

        
    }//GEN-LAST:event_tabelaServicoMouseClicked

    private void excluirServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirServicoActionPerformed
        // TODO add your handling code here:

        //Deleta o campo selecionado da tabela e mostra a tabela atualizada
        
        
        deletarProduto();
        listarValores();

      
    }//GEN-LAST:event_excluirServicoActionPerformed

    private void apagarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarCamposActionPerformed
        // TODO add your handling code here:

        //Apaga os campos dos campos de texto e mostra os valores da tabela
        
        apagaCampos();

        
    }//GEN-LAST:event_apagarCamposActionPerformed

    private void alterarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarServicoActionPerformed
        // TODO add your handling code here:

        //Altera os valores e depois mostra os valores atualizados
        
        AlterarServico();
        listarValores();

        
    }//GEN-LAST:event_alterarServicoActionPerformed

    private void buscarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarFiltroActionPerformed
        // TODO add your handling code here:

        // Corre o campo para ver se tem algo escrito e pesquisar por filtro, se não tiver faz a busca completa

        if (txtFiltro.getText().length() > 0) {
        listarValoresFiltro();
        }else{
            listarValores();
        }

    }//GEN-LAST:event_buscarFiltroActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // TODO add your handling code here:
        
         new PrincipalView().setVisible(true);
         dispose();
        
    }//GEN-LAST:event_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServicoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Voltar;
    private javax.swing.JButton alterarServico;
    private javax.swing.JButton apagarCampos;
    private javax.swing.JButton buscarFiltro;
    private javax.swing.JButton cadastrarServico;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton excluirServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaServico;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtFiltro;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables


private void cadastrarServico() {

        String tipo = txtTipo.getText();
        String descricao = txtDescricao.getText();
        Double preco = Double.valueOf(txtPreco.getText());
        Servico servico = new Servico(tipo, descricao, preco);
        ServicoDB mysql = new ServicoDB();

        try {
            mysql.insertServico(servico);
        } catch (Exception ex) {
            System.out.println("erro no view para inserir servico");
            throw new RuntimeException(ex);
        }

    }


//Lista os valores na tabela
 private void listarValores() {

        try {

            ServicoDB servico = new ServicoDB();
            DefaultTableModel model = (DefaultTableModel) tabelaServico.getModel();
            model.setNumRows(0);

            String filtro = txtId.getText();
            System.out.println(filtro);

            ArrayList<Servico> resultado = (ArrayList<Servico>) servico.selectServico();
            for (int num = 0; num < resultado.size(); num++) {

                model.addRow(new Object[] {

                        resultado.get(num).getIdServico(),
                        resultado.get(num).getTipoServico(),
                        resultado.get(num).getDescricaoServico(),
                        resultado.get(num).getPrecoServico()
                });
            }

        } catch (Exception e) {
            System.out.println("erro");
            throw new RuntimeException(e);

        }
    }
 
 
 private void listarValoresFiltro() {

        try {

            ServicoDB servico = new ServicoDB();
            DefaultTableModel model = (DefaultTableModel) tabelaServico.getModel();
            model.setNumRows(0);

           String filtro = null;
            
            int valorCombo = combo.getSelectedIndex();
            
            if(valorCombo == 0 ){
                
                filtro = "Where idServico= "+txtFiltro.getText();
            }else{
                
                filtro = "Where tipoServico LIKE '%"+txtFiltro.getText()+"%'";
            }

            ArrayList<Servico> resultado = (ArrayList<Servico>) servico.selectServico(filtro);
            for (int num = 0; num < resultado.size(); num++) {

                model.addRow(new Object[] {

                        resultado.get(num).getIdServico(),
                        resultado.get(num).getTipoServico(),
                        resultado.get(num).getDescricaoServico(),
                        resultado.get(num).getPrecoServico()
                });
            }

        } catch (Exception e) {
            System.out.println("erro");
            throw new RuntimeException(e);

        }
    }
 
 private void CarregarServico() {

        int setar = tabelaServico.getSelectedRow();

        txtId.setText(tabelaServico.getModel().getValueAt(setar, 0).toString());
        txtTipo.setText(tabelaServico.getModel().getValueAt(setar, 1).toString());
        txtDescricao.setText(tabelaServico.getModel().getValueAt(setar, 2).toString());
        txtPreco.setText(tabelaServico.getModel().getValueAt(setar, 3).toString());

    }
 
 
 private void deletarProduto() {

       

        int idServico = Integer.parseInt(txtId.getText());

        Servico servico = new Servico(idServico);

        ServicoDB mysql = new ServicoDB();

        try {
            mysql.deleteServico(idServico);
        } catch (Exception ex) {
            System.out.println("erro no view para excluir servico");
            throw new RuntimeException(ex);
        }

    }
 
 
   private void apagaCampos(){
      
      txtId.setText("");
      txtTipo.setText("");
      txtDescricao.setText("");
      txtPreco.setText("");
      
  }
   
   
   private void AlterarServico() {

        

       int id = Integer.parseInt(txtId.getText());
       String tipo = txtTipo.getText();
        String descricao = txtDescricao.getText();
        Double preco = Double.valueOf(txtPreco.getText());

        Servico servico = new Servico(id, tipo, descricao, preco);

        ServicoDB mysql = new ServicoDB();

        try {
            mysql.updateServico(servico);
        } catch (Exception ex) {
            System.out.println("erro no view para alterar servico");
            throw new RuntimeException(ex);
        }

    }
 

}
